stages:
  - build
  - archive

build_project:
  stage: build
  script:
    - echo "Build for $SCHEME"
    - xcodebuild clean -project "Hello World.xcodeproj" -scheme "$SCHEME" | xcpretty
    - xcodebuild build-for-testing -project "Hello World.xcodeproj" -scheme "$SCHEME" -destination "platform=iOS Simulator,name=iPhone X,OS=11.4" | xcpretty -s

archive_project:
  stage: archive
  script:
    - xcodebuild clean archive -archivePath "build/Hello World" -scheme "$SCHEME" -allowProvisioningUpdates | xcpretty
#    - xcodebuild -exportArchive -archivePath "build/Hello World.xcarchive" -exportPath "build/Hello World.ipa" -allowProvisioningUpdates -exportOptionsPlist adhoc.plist | xcpretty 
  artifacts:
    paths:
      - build/
