stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project "Hello World.xcodeproj" -scheme "Hello World" | xcpretty
    - xcodebuild build-for-testing -project "Hello World.xcodeproj" -scheme "Hello World" -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4' | xcpretty -s
