stages:
  - build
  - archive

build_project:
  stage: build
  script:
    - echo "Build for $SCHEME"
    - xcodebuild clean -project "Hello World.xcodeproj" -scheme "$SCHEME" | xcpretty
    - xcodebuild build-for-testing -project "Hello World.xcodeproj" -scheme "$SCHEME" -destination "platform=iOS Simulator,name=iPhone X,OS=11.4" | xcpretty -s

archive_project:
  stage: archive
  script:
    - xcodebuild clean archive -archivePath "build/$SCHEME" -scheme "$SCHEME" -allowProvisioningUpdates | xcpretty
#    - xcodebuild -exportArchive -archivePath "build/Hello World.xcarchive" -exportPath "build/Hello World.ipa" -allowProvisioningUpdates -exportOptionsPlist adhoc.plist | xcpretty 
    - mkdir -p "/Users/mini/Mac Mini/Hello World/$SCHEME/$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA"
    - cp -r "build/$SCHEME.xcarchive/Products/Applications/" "/Users/mini/Mac Mini/Hello World/$SCHEME/$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA/"
#  artifacts:
#    paths:
#      - "build/$SCHEME.xcarchive/Products/Applications/"
